### ISSUE TITLE
No such file or directory: 'mvn': 'mvn'

### ISSUE THREAD

**Issue by RuihanZhang2015** [saalfeldlab/stitching-spark#32]
When I typed `python build-spark-local.py`, it shows the following errors, what should I do?

Traceback (most recent call last):
  File "build-spark-local.py", line 12, in <module>
    run_build(base_folder, build_args)
  File "/mp/nas2/ruihan/stitching-spark/build.py", line 8, in run_build
    subprocess.call(cmd_args, cwd=base_folder)
  File "/home/ruihan/anaconda3/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/ruihan/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/ruihan/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mvn': 'mvn'

**Comment by BioinfoTongLI** [comment]
Hi @RuihanZhang2015,
I've had the same error. I think it's caused by a missing prerequisite: [maven](https://maven.apache.org/).
I installed it with `sudo apt-get install maven` and the building worked fine.

Best,
Tong
