### ISSUE TITLE
BloscCompression Class Not Found

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [saalfeldlab/stitching-spark#39]
I am operating on a RedHat Linux server where I do not have sudo privileges.  I thus took a different approach to testing this out.

- cd /archive/MIL/dean/git/external
- git clone https://github.com/saalfeldlab/n5-utils.git
- cd n5-utils/
- git submodule update --init --recursive
- module load maven/3.5.3
- ./install $HOME/bin
- I added $HOME/bin to my .bashrc profile, rebooted terminal.
- I then ran it on the output of BigStitcher-Spark... n5-view -i /archive/MIL/dean/2022-04-24-big-stitcher-spark-test/fused.n5 -d /ch488/s0
- The data was properly loaded and displayed by BigDataViewer, but threw the following error:
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Native.register(Native.java:1647)
	at com.sun.jna.Native.register(Native.java:1360)
	at org.blosc.IBloscDll.<clinit>(IBloscDll.java:15)
	at org.blosc.JBlosc.init(JBlosc.java:30)
	at org.blosc.JBlosc.<init>(JBlosc.java:24)
	at org.janelia.saalfeldlab.n5.blosc.BloscCompression.<clinit>(BloscCompression.java:70)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.janelia.saalfeldlab.n5.CompressionAdapter.update(CompressionAdapter.java:82)
	at org.janelia.saalfeldlab.n5.CompressionAdapter.getJsonAdapter(CompressionAdapter.java:166)
	at org.janelia.saalfeldlab.n5.AbstractGsonReader.<init>(AbstractGsonReader.java:58)
	at org.janelia.saalfeldlab.n5.N5FSReader.<init>(N5FSReader.java:116)
	at org.janelia.saalfeldlab.n5.N5FSReader.<init>(N5FSReader.java:136)
	at org.janelia.saalfeldlab.N5Factory.createN5FS(N5Factory.java:259)
	at org.janelia.saalfeldlab.N5Factory.createN5(N5Factory.java:207)
	at org.janelia.saalfeldlab.N5Factory.createN5Reader(N5Factory.java:186)
	at org.janelia.saalfeldlab.View.call(View.java:281)
	at org.janelia.saalfeldlab.View.call(View.java:175)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at org.janelia.saalfeldlab.View.main(View.java:514)

Not sure if it is only needed if compression is used when the N5 data is saved.  But thought I would report it nonetheless.

**Comment by mkitti** [comment]
Thanks Kevin, I see it now.

**Comment by mkitti** [comment]
This is compounded by several issues:
1. The `libblosc.so` native library is usually distributed by FIJI in `Fiji.app/lib/linux64/libblosc.so`
2. Linux distributions typically package this as `libblosc.so.1`
3. Sometimes the development packages (e.g. libblosc-dev) maybe provide "libblosc.so"

In the near term, users can can extract libblosc.so from the Fiji.app folder and add it to the library load path (e.g. `LD_LIBRARY_PATH`). Please consult your local system administrator on how to best do this.

Another option may be to install a prepared libblosc, blosc, or c-blosc package or their dev companion packages for your system, and symlink libblosc.so.1 to libblosc.so.

A more intensive option involves building c-blosc from scratch. See the README at https://github.com/Blosc/c-blosc

In the long term, Fiji.app and the relevant Saalfeld Lab packages should probably link against libblosc.so.1 rather than libblosc.so so that the native library could be provided by the Linux system if not provided by FIJI.

cc: @ctrueden
