### ISSUE TITLE
Increase ImageJ memory for org.janelia.stitching.StitchingSpark

### ISSUE THREAD

**Issue by carshadi** [saalfeldlab/stitching-spark#43]
Hi,

I am trying to run the stitch step on a Dataproc cluster, but get the following ImageJ-related OOM. 
Using larger memory nodes does not make a difference in this case, since it's the ImageJ configuration. 
How can I increase the memory (and possibly threads?) available to ImageJ when running on Dataproc?
Usually I would just start ImageJ with `-Xmx` but it's not clear to me how to do that here...
```
Overlapping pairs count = 3240
Retaining only 1800 adjacent pairs of them
************** Iteration 0 **************
Removed 0 redundant pairs from the cached pairwise file
Broadcasting flatfield correction images
Loading flat-field components:
  gs://xxxx/spark-stitching-test/tile_config-flatfield/S.tif
  gs://xxxx/spark-stitching-test/tile_config-flatfield/T.tif
>>>>>>>>>>>>>>>>>>>>>>>>>>>
<Out of memory>
<All available memory (1820MB) has been>
<used. To make more available, use the>
<Edit>Options>Memory & Threads command.>
>>>>>>>>>>>>>>>>>>>>>>>>>>>
22/06/01 23:04:00 INFO org.sparkproject.jetty.server.AbstractConnector: Stopped Spark@76bc265e{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at net.imglib2.img.basictypeaccess.array.AbstractFloatArray.<init>(AbstractFloatArray.java:50)
	at net.imglib2.img.basictypeaccess.array.FloatArray.<init>(FloatArray.java:47)
	at net.imglib2.img.basictypeaccess.array.FloatArray.createArray(FloatArray.java:58)
	at net.imglib2.img.basictypeaccess.array.FloatArray.createArray(FloatArray.java:43)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:91)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:68)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:75)
	at org.janelia.flatfield.FlatfieldCorrection.copyImage(FlatfieldCorrection.java:126)
	at org.janelia.flatfield.FlatfieldCorrection.loadCorrectionImages(FlatfieldCorrection.java:114)
	at org.janelia.stitching.PipelineStitchingStepExecutor.computePairwiseShifts(PipelineStitchingStepExecutor.java:397)
	at org.janelia.stitching.PipelineStitchingStepExecutor.preparePairwiseShiftsMulti(PipelineStitchingStepExecutor.java:346)
	at org.janelia.stitching.PipelineStitchingStepExecutor.run(PipelineStitchingStepExecutor.java:108)
	at org.janelia.stitching.StitchingSpark.run(StitchingSpark.java:88)
	at org.janelia.stitching.StitchingSpark.main(StitchingSpark.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
The flatfield solution Tiffs are both 1.3GB.

Thanks,
Cameron

**Comment by carshadi** [comment]
I just had to increase my spark driver memory from `3016m` to `8192m` a la `spark:spark.driver.memory` and it's running now. Closing this.
